# Generated by Django 4.1 on 2023-10-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
