# Generated by Django 4.1 on 2023-10-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
