# Generated by Django 4.1.12 on 2023-11-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_osoba_plec'),
        ('testapp', '0007_alter_stanowisko_opis'),
    ]

    operations = [
    ]
