# Generated by Django 4.1.12 on 2023-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_merge_20231111_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
