# Generated by Django 4.1 on 2023-11-13 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0012_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Osoba', to=settings.AUTH_USER_MODEL),
        ),
    ]
