# Generated by Django 4.1 on 2023-11-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0014_alter_osoba_options_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['id'], 'permissions': [('can_view_other_persons', 'Test')]},
        ),
        migrations.AlterField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
