# Generated by Django 4.1 on 2023-11-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_osoba_options_alter_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='stanowisko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.stanowisko'),
        ),
    ]
